### ISSUE TITLE
in Braid, cameras cannot be synchronized more than once

### ISSUE THREAD

**Issue by elhananby** [strawlab/strand-braid#1]
Hi everyone,
I had this issue a few times recently, where Braid would crash with this error message:
`thread 'main' panicked at 'Received data twice: camera=Basler_23088879, orig frame=10921. new frame=10921', flydra2/src/bundled_data.rs:136:13`
`note: run with 'RUST_BACKTRACE=1' environment variable to display a backtrace`
`Error: channel is empty and disconnected`
`Caused by: channel is empty and disconnected`
`Jan 22 12:21:47.171 ERROR flydra2_mainbrain: done listening for trigger clock data: sender hung up.`

Thanks,
Elhanan

**Comment by astraw** [comment]
Could it be that you synchronized the cameras more than once upon running Braid? In theory this should work, in reality there are still bugs here, I'm afraid.

**Comment by astraw** [comment]
Also, could the set of cameras in the calibration be different than the set of currently connected cameras? I think might also result in this error. Again, this should work but in reality there are likely bugs with this still.

**Comment by elhananby** [comment]
> Could it be that you synchronized the cameras more than once upon running Braid? In theory this should work, in reality there are still bugs here, I'm afraid.

Yes, I think that's the issue - i didn't have time to test it too much yesterday, but it does seem like that this only happen if I do the camera synchronization more than once.
Should I keep this thread as an open bug, or close it for now?

**Comment by astraw** [comment]
I renamed the bug. Let's keep it open until it is fixed.

**Comment by astraw** [comment]
As of release 0.10.0, Braid automatically synchronizes the cameras at program start and there is no need (or support) for resynchronizing them. Therefore, I also removed the synchronize button from the UI. 14ba9b1d7571f8d60466686644314ffe8232ef8c
