### ISSUE TITLE
when running within Braid, keep URL constant for Strand Camera

### ISSUE THREAD

**Issue by elhananby** [strawlab/strand-braid#11]
Hi Andrew,

just had a couple (non-essential) feature request - would it be possible to define the port on which each strand_cam instance opens in the .toml file (similar to the mainbrain)? I like to have all the camera windows open, but need to change the address every time I restart braid.
Also, it would be great if there was an option to save the parameters set for each camera in the configuration to the .toml file.

Thanks,
Elhanan

**Comment by astraw** [comment]
Do you mean standalone strand cam? If so, you can start it with the '--http-server-addr' command line argument to do this.

Within braid, I actually plan to implement an alternate solution where the braid program will proxy access to the cameras via a URL like http://localhost:44444/camera/Basler-12345/ . The URL will stay stable then and, even better, if you connect to the machine with an SSH tunnel you will not have to constantly reassign ports. I believe that would address your issue, correct?

Regarding your second feature request (which ideally would be done in a separate ticket) I am actually just now implementing the ability to specify a camera settings file to be loaded at start and then the parameters also saved to the braidz file. (What will not be saved is any paramaters that have been changed after the initial startup.)

**Comment by astraw** [comment]
Regarding the object detection configuration: now I realize that you probably mean the [`image_tracker_types::ImPtDetectCfg`](https://strawlab.org/strand-braid-api-docs/latest/image_tracker_types/struct.ImPtDetectCfg.html) parameters. In terms of camera settings such as exposure time, as of c2ddfc585d11d419ac7cc4f0e32b0253ca78024c, these will now be saved to the .braidz file. I created a new issue with this specific request: #12. I will change the title of this issue to reflect the request for constant URL for strand cam when run from braid.

**Comment by elhananby** [comment]
Sorry for the late reply - yeah, the solution you suggested is exactly what I mean.
Thanks for all the help

**Comment by astraw** [comment]
I added proxying from Braid to Strand Cam, which keeps a fixed URL, in 4efb615975c613d21f9ebf439475ac983e492854. This is available in the 0.12.0-alpha.4 release which we are now testing for the 0.12 release.
