### ISSUE TITLE
Hardware configurations and set up

### ISSUE THREAD

**Issue by GuilhermeMEESantos** [strawlab/strand-braid#13]
Good afternoon. I have been reading and analysing this open-source project and I have questions regarding the usual hardware set up for implementing braid. 

I know that specific cameras need to be used but I was wondering about the more physical aspects of the set-up. How do you connect the cameras? Does it use a switch or several switches and connect them to the main pc where the app will be running? What is the usual hardware configuration? 

Is there any guide about the hardware and more physical aspects of this system? I've read the [User's Guide](https://strawlab.github.io/strand-braid/braid-and-strand-camera.html) but it didn't answer my questions for it focused on the software.

I am looking forward to hearing from you.

**Comment by astraw** [comment]
There is a [hardware selection section](https://github.com/strawlab/strand-braid/blob/main/strand-braid-user/users-guide/src/hardware-selection.md) in the user's guide but indeed it does not discuss things at the level you are asking.

All cameras must share the same physical trigger input, so this is an additional cable beyond the GigE or USB3 cable to each camera.

With USB3 each camera needs a direct connection to a PC and it is quite simple as long as you have enough USB3 ports and bandwidth to handle them on the PC.

It seems you are mainly asking about network topologies with GigE cameras. With network cameras, the issues are potentially somewhat complex. I will create a new section in the documentation describing some thoughts on this and I will update this issue when there is something to look at.

**Comment by GuilhermeMEESantos** [comment]
Thank you so much for your answer and appreciate you taking the time to create a new documentation section about this. 
But your answer has been very helpful, thank you.

I wish you a continuation of good work.
Best regards,
GuilhermeMEESantos

**Comment by astraw** [comment]
I found [this page on Basler's site](https://docs.baslerweb.com/network-configuration-(gige-cameras)) which goes some way towards explaining GigE network topologies. The information there is by no means exhaustive but it is useful as far as it goes.
