### ISSUE TITLE
braid doesn't shut down with ctrl-c (0.12.0-alpha1 - 2022-06-16)

### ISSUE THREAD

**Issue by florisvb** [strawlab/strand-braid#19]
I'm testing out braid 0.12.0-alpha1 - 2022-06-16 and so far so good. Just a minor annoyance, but I am finding that when I hit ctrl-c in the terminal window where I start braid it does not actually kill braid. I have to find the process ID (ps aux | grep braid) and then hard kill it (sudo kill -9 PID).

**Comment by astraw** [comment]
Thanks for the report.

I think some issues like this may have crept in as I tried to streamline concurrency. Can you try [0.12.0-alpha.2](https://github.com/strawlab/strand-braid/releases/tag/strand-braid%2F0.12.0-alpha.2)? I just made this new pre-release. It will be useful to know if you see the same problem there as I have been working on potentially relevant issues.

This is exactly the kind of stuff that I hope to catch before making a "real release" which is one reason why these are just alpha pre-releases.

**Comment by astraw** [comment]
I think this is fixed in 0fe4f07488f7e998bc43881c3b9074c1046fe53b. Let's re-open this report if we find otherwise.
