### ISSUE TITLE
braid web ui does not autoupdate with >11 cameras

### ISSUE THREAD

**Issue by florisvb** [strawlab/strand-braid#20]
This may not be a braid issue per se, but I find that when I run braid with 12x cameras (basler ace2's) each running at 1920x1200 at 100 fps, when I add my 12th camera the braid UI loaded with firefox or chrome will 'freeze'. That is, the record button won't change when I press it, but the command line indicates that the button gets pressed, and the number of frames processed won't update either. If I refresh the browser window, however, everything does refresh. 

So far as I can tell, this is just a cosmetic issue, and is probably more due to the browser than braid. But perhaps more information is being provided to the browser UI than is necessary? I have noticed that the VIRT column given by htop for all the browser related processes is insanely large in my use case (>1 TB for many process IDs). 

I was stumped by this for a while, until I realized it was just a browser/cosmetic issue..

**Comment by astraw** [comment]
Hi Floris, yes sometimes after running experiments overnight we need to reload the webpage... Unfortunately I do not know where it is. I do think this is a real bug and will keep this page open as a reminder. Nevertheless, indeed simply reloading the page has always been enough to keep moving.

**Comment by astraw** [comment]
I think I at least partially fixed this in 9d8607a4c90db2ee043e7c7c6a2405cf00353b41. Please re-open this issue if the problem persists.
