### ISSUE TITLE
Empty archive when saving AprilTag

### ISSUE THREAD

**Issue by elhananby** [strawlab/strand-braid#6]
Hi Andrew, 

I tried using the apriltag detection for calibration, and I can see that it detects the tags successfully for the cameras and saves a zip file. The zipfile contains an csv file, however if i try to extract it I get an `empty archive` error; if I try to open it from within the zip, it shows only one row with Chinese characters.

edit #2: nevermind, realized I was just being dumb and opening the csv with the wrong encoding. I am now able to open the csv file from within the zip, but still not extract it.

edit: I also tried using the alternative (using `gst-plugin-apriltag`), however then I get an error: `ERROR: pipeline could not be constructed: no element "filesrc".` I made sure to run `export GST_PLUGIN_PATH='pwd'/../target/release` and install all required gst-streamer packages.

Thanks for all the quick help!
Elhanan

**Comment by astraw** [comment]
How are you trying to read the `apriltags.csv.gz` file? Pandas should be able to open it directly (despite being gz compressed) with:

```python
pd.read_csv('apriltags.csv.gz', comment='#')
```

what's the error you are getting?

For gstreamer, if `filesrc` cannot be found by streamer, it seems you may be missing some of the core plugins. Can you tell Ubuntu to install more of the gtreamer packages?

**Comment by elhananby** [comment]
Yeah, I eventually did just that, and it opened it with pandas correctly (although I had to specify `skiprows=8` due to some additional rows at the beginning of the file) and performed the calibration successfully. Should I expect similar reprojection error values as with MCSC? I got around 1.5 for 800x600 cameras and ~4 for the HD cameras.

Regarding gstreamer, I will check it again a bit later and let you know.

Thanks,
Elhanan

**Comment by astraw** [comment]
As this is wandering a bit from the original issue and also is more of a discussion topic rather than an issue per se with the Strand/Braid, I would prefer to have this conversation at our group. I answered the last question about reprojection errors at https://groups.google.com/g/multicams/c/IwWpcpQaA84.
